using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using TestCommon.Model;

namespace Xtensive.Orm.BulkOperations.Tests
{
  internal class TagTest : BulkOperationBaseTest
  {
    [Test]
    public void BulkDelete()
    {
      using (var session = Domain.OpenSession())
      using (var trx = session.OpenTransaction()) {
        _ = new Bar(session) { Name = "test" };
        var allCommands = new List<string>();

        session.Events.DbCommandExecuting += SqlCapturer;
        _ = session.Query.All<Bar>().Tag("bulkDeleteTag").Where(a => a.Name == "test").Delete();
        session.Events.DbCommandExecuting -= SqlCapturer;

        Assert.That(allCommands, Has.Some.Contains("/*bulkDeleteTag*/"));
        trx.Complete();

        void SqlCapturer(object sender, DbCommandEventArgs args) => allCommands.Add(args.Command.CommandText);
      }
    }

    [Test]
    public async Task BulkDeleteAsync()
    {
      await using (var session = await Domain.OpenSessionAsync())
      await using (var trx = session.OpenTransaction()) {
        _ = new Bar(session) { Name = "test" };
        var allCommands = new List<string>();

        session.Events.DbCommandExecuting += SqlCapturer;
        _ = await session.Query.All<Bar>().Tag("bulkDeleteAsyncTag").Where(a => a.Name == "test").DeleteAsync();
        session.Events.DbCommandExecuting -= SqlCapturer;

        Assert.That(allCommands, Has.Some.Contains("/*bulkDeleteAsyncTag*/"));
        trx.Complete();

        void SqlCapturer(object sender, DbCommandEventArgs args) => allCommands.Add(args.Command.CommandText);
      }
    }

    [Test]
    public void BulkUpdate()
    {
      using (var session = Domain.OpenSession())
      using (var trx = session.OpenTransaction()) {
        _ = new Bar(session) { Name = "test", Count = 3 };
        var allCommands = new List<string>();

        session.Events.DbCommandExecuting += SqlCapturer;
        _ = session.Query.All<Bar>().Tag("bulkUpdateTag").Where(a => a.Name == "test").Set(a => a.Count, 5).Update();
        session.Events.DbCommandExecuting -= SqlCapturer;

        Assert.That(allCommands, Has.Some.Contains("/*bulkUpdateTag*/"));
        trx.Complete();

        void SqlCapturer(object sender, DbCommandEventArgs args) => allCommands.Add(args.Command.CommandText);
      }
    }

    [Test]
    public async Task BulkUpdateAsync()
    {
      await using (var session = await Domain.OpenSessionAsync())
      await using (var trx = session.OpenTransaction()) {
        _ = new Bar(session) { Name = "test", Count = 3 };
        var allCommands = new List<string>();

        session.Events.DbCommandExecuting += SqlCapturer;
        _ = await session.Query.All<Bar>().Tag("bulkUpdateAsyncTag").Where(a => a.Name == "test")
          .Set(a => a.Count, 5).UpdateAsync();
        session.Events.DbCommandExecuting -= SqlCapturer;

        Assert.That(allCommands, Has.Some.Contains("/*bulkUpdateAsyncTag*/"));
        trx.Complete();

        void SqlCapturer(object sender, DbCommandEventArgs args) => allCommands.Add(args.Command.CommandText);
      }
    }

    [Test]
    public void BulkUpdateWithLimitationCarriesTag()
    {
      // SQL Server's UPDATE TOP(N)/DELETE TOP(N) path is generated by a driver-specific
      // compiler override that bypasses the shared base-compiler comment emission,
      // so it needs its own regression coverage.
      CheckLimitationSupported();

      using (var session = Domain.OpenSession())
      using (var trx = session.OpenTransaction()) {
        _ = new Bar(session) { Name = "test", Count = 3 };
        _ = new Bar(session) { Name = "test", Count = 3 };
        var allCommands = new List<string>();

        session.Events.DbCommandExecuting += SqlCapturer;
        _ = session.Query.All<Bar>().Tag("bulkUpdateLimitTag").Where(a => a.Name == "test").Take(1)
          .Set(a => a.Count, 5).Update();
        session.Events.DbCommandExecuting -= SqlCapturer;

        Assert.That(allCommands, Has.Some.Contains("/*bulkUpdateLimitTag*/"));
        trx.Complete();

        void SqlCapturer(object sender, DbCommandEventArgs args) => allCommands.Add(args.Command.CommandText);
      }
    }

    [Test]
    public void BulkDeleteWithLimitationCarriesTag()
    {
      CheckLimitationSupported();

      using (var session = Domain.OpenSession())
      using (var trx = session.OpenTransaction()) {
        _ = new Bar(session) { Name = "test" };
        _ = new Bar(session) { Name = "test" };
        var allCommands = new List<string>();

        session.Events.DbCommandExecuting += SqlCapturer;
        _ = session.Query.All<Bar>().Tag("bulkDeleteLimitTag").Where(a => a.Name == "test").Take(1).Delete();
        session.Events.DbCommandExecuting -= SqlCapturer;

        Assert.That(allCommands, Has.Some.Contains("/*bulkDeleteLimitTag*/"));
        trx.Complete();

        void SqlCapturer(object sender, DbCommandEventArgs args) => allCommands.Add(args.Command.CommandText);
      }
    }

    private void CheckLimitationSupported()
    {
      if (!Domain.StorageProviderInfo.Supports(Providers.ProviderFeatures.UpdateLimit)) {
        throw new IgnoreException("Test is inconclusive for current provider");
      }
    }
  }
}
