name: Build and Test
on:
  pull_request:
    branches: [ master-servicetitan ]
env:
  DO_TargetFrameworks: net8.0
jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - name: Build
        run: dotnet build -c Release -v q
      - name: Tests.Core
        run: dotnet test -c Release --no-build -v n Orm/Xtensive.Orm.Tests.Core/Xtensive.Orm.Tests.Core.csproj --filter 'TestCategory!=Mute'
